function [ModelNum,MinDischargeArea,ActualDischargeArea] = ...
    ReliefValveSelectorFunc(Commodity,Cv,MAWP,Temp,SetPressure,Z, ...
    PressOver,Kc)
% -------------------------------------------------------------------------
