%% Point to a relevent copy of the lo2-storage-gui config file

filename = 'SpecialTopics/generate_fds_for_lo2/mdrt_format_config.json';
filename = '/Users/nick/Developer/demo/p0a-lo2-storage-gui/mdrt_format_config.json';
json_lines = readlines(filename);

% Strip out comments to make Matlab's parser happy

prefix = '^\s*\/\/';
stripped_array = json_lines(cellfun(@isempty, regexp(json_lines, [prefix, '.*'], 'match', 'once')));

json = jsondecode( strjoin(stripped_array, '\n'));


%% Storage Vessel Sensor List
json_tanks = json.display_config.tanks;
tank_names = fields(json_tanks);
tank_sensor_types = fields(json_tanks.(tank_names{1}).sensors);


% %% Storage Vessel Sensor List Generation
% json_tanks = json.display_config.tanks;
% tank_names = fields(json_tanks);
% 
% for n = 1:numel(tank_names)
%     json_this_tank = json_tanks.(tank_names{n});
%     tank_sensor_types = fields(json_this_tank.sensors)
%     tank_str = json_this_tank.tag_str;
%     for s = 1:numel(tank_sensor_types)
%         this_sensor_str = tank_sensor_types{s};
%         this_sensor_fd_str = json_this_tank.sensors.(this_sensor_str)
%         switch this_sensor_fd_str
%             case 'ullage_press_1'
% 
%             case 'liquid_level'
% 
%             case 'liquid_volume_percent'
% 
%         end
% 
%     end



%% State Variable Creation

fprintf('\n\nProcessing State FDs\n\n');
data_configs = fields(json.data_config.fds);

processed_state_finds = {};

for n = 1:numel(data_configs)
    this_json_str = data_configs{n};
    this_json_fd = json.data_config.fds.(this_json_str);

    if ~any(contains(fields(this_json_fd), 'cal_curve'))
        % fprintf('Skipping %s\n', this_json_str)
        continue
    end

    this_cal_curve = this_json_fd.cal_curve;
    this_fd_str = this_json_fd.original_fd_string;

    switch this_cal_curve.type
        case 'DiscreteValve'
            fprintf('Processing %s\n', this_json_str)
            open_fd = load_fd_by_name(this_json_fd.cal_curve.fd_open);
            close_fd = load_fd_by_name(this_json_fd.cal_curve.fd_close);
            fd = make_state_fd_from_inds(this_fd_str, open_fd, close_fd);
            save_fd_to_disk(fd);
            processed_state_finds = vertcat(processed_state_finds, fd.ID);
        otherwise
            continue
    end
end



%% Command Variable Creation

fprintf('\n\nProcessing Command Params\n\n')
data_configs = fields(json.display_config.dcvs);

for n = 1:numel(data_configs)
    this_json_str = data_configs{n};

    fprintf('Processing %s\n', this_json_str)
    this_json_fd = json.display_config.dcvs.(this_json_str);

    if ~any(contains(fields(this_json_fd), 'commands'))
        warning('Skipping %s\n', this_json_str)
        continue
    end
    
    this_cmd_array = this_json_fd.commands;
    this_fd_str = this_json_fd.original_fd_string;

    cmds = fieldnames(this_json_fd.commands);
    if any(contains(cmds, 'position'))
        % Process as proportional valve
        this_cmd_fd_str = [this_json_fd.commands.position, ' Param' ];
        if contains (this_cmd_fd_str, this_fd_str)
            fprintf('Skipping "%s" - Command Param is already retrievable\n', this_cmd_fd_str)
            continue
        end
    elseif any(contains(cmds, 'open_cmd'))
        % Process as discrete
        this_cmd_fd_str = [this_json_fd.commands.open_cmd{1}, ' Param' ];
        if contains(this_cmd_fd_str, this_fd_str)
            % If we are retrieving against a temporary valve, then the
            % defined state will look like `DCVNC-1234 State` and the
            % commands will look like `CB1 Discrete Out 1 Ctl Param`
            fprintf('Skipping "%s" - Command Param is already retrievable\n', this_cmd_fd_str)
            continue
        end
    else
        % WTF is this?
        warning('%s could not be processed - unable to identify command string', this_fd_str);
        continue
    end
    
    try
        cmd_fd = load_fd_by_name(this_cmd_fd_str);
    catch
        msg = sprintf(['Unable to find matching command FD in the retrieved data\n' ...
            '%s\nLooked for %s'], this_fd_str, this_cmd_fd_str);
        warning(msg);
        continue
    end
    
    fd = make_valve_cmd_fd(this_fd_str, cmd_fd);
    save_fd_to_disk(fd);
        
end


%% Sensor Generation

fprintf('\n\nProcessing Sensor Values\n\n')
data_configs = fields(json.data_config.fds);
tanks = fields(json.display_config.tanks);
json_tank_sensors = {};
all_tank_sensor_names = {};

to_process = [
    struct( 'entry_str', 'CB8AnalogIn10Mon', ...
            'container', json.data_config.fds, ...
            'fd_to_load', 'CB8 Analog In 10  Mon RAW', ...
            'fd_to_save', 'LO2 PT-2921 Press  Mon MCS', ...
            'output_units', 'psig' ...
            );
    struct( 'entry_str', 'CB8AnalogIn11Mon', ...
            'container', json.data_config.fds, ...
            'fd_to_load', 'CB8 Analog In 11  Mon RAW', ...
            'fd_to_save', 'LO2 PT-2922 Press  Mon MCS', ...
            'output_units', 'psig' ...
            );
    struct( 'entry_str', 'CB7AnalogIn04Mon', ...
            'container', json.data_config.fds, ...
            'fd_to_load', 'CB7 Analog In 04  Mon RAW', ...
            'fd_to_save', '', ...
            'output_units', 'inwc' ...
            );

    % MARS-32 Data
    struct( 'entry_str',  'LO2PT_2902PressSensorMon', ...
            'container',  json.data_config.fds, ...
            'fd_to_load', 'LO2 PT-2902 Press Sensor  Mon RAW', ...
            'fd_to_save', 'LO2 PT-2902 Press Sensor  Mon MCS', ...
            'output_units', 'psid' ...
            );
    struct( 'entry_str', 'mars_32LiquidColumnHeight', ...
            'container',  json.data_config.fds, ...
            'fd_to_load', 'LO2 PT-2902 Press Sensor  Mon MCS', ...
            'fd_to_save', 'MARS-32 Liquid Column Height',...
            'output_units', 'gal' ...
            );        
    struct( 'entry_str', 'mars_32LiquidVolumeGallons', ...
            'container', json.data_config.fds, ...
            'fd_to_load', 'MARS-32 Liquid Column Height', ...
            'fd_to_save', 'MARS-32 Liquid Volume Gallons', ...
            'output_units', 'gal' ...
            );
    struct( 'entry_str', 'mars_32LiquidVolumePercent', ...
            'container', json.data_config.fds, ...
            'fd_to_load', 'MARS-32 Liquid Column Height', ...
            'fd_to_save', 'MARS-32 Liquid Volume Percent', ...
            'output_units', '%' ...
            );       

    % MARS-144 Data
    struct( 'entry_str', 'CB8AnalogIn09Mon', ...
            'container', json.data_config.fds, ...
            'fd_to_load', 'CB8 Analog In 09  Mon RAW', ...
            'fd_to_save', 'LO2 PT-2920 Press Sensor  Mon MCS', ...
            'output_units', 'inwc' ...
            );
    struct( 'entry_str', 'mars_144LiquidColumnHeight', ...
            'container', json.data_config.fds, ...
            'fd_to_load', 'LO2 PT-2920 Press Sensor  Mon MCS', ...
            'fd_to_save', 'MARS-144 Liquid Column Height', ...
            'output_units', 'in' ...
            );
    struct( 'entry_str', 'mars_144LiquidVolumeGallons', ...
            'container', json.data_config.fds, ...
            'fd_to_load', 'mars-144 liquid column height', ...
            'fd_to_save', 'MARS-144 Liquid Volume Gallons', ...
            'output_units', 'gal' ...
            );
    struct( 'entry_str', 'mars_144LiquidVolumePercent', ...
            'container', json.data_config.fds, ...
            'fd_to_load', 'mars-144 liquid column height', ...
            'fd_to_save', 'MARS-144 Liquid Volume Percent', ...
            'output_units', '%' ...
            );

    % MARS LN2 Storage Calculations
    % MARS-11 Tank
    struct( 'entry_str', 'PT3917', ...
            'container', struct('PT3917', ...
                struct('cal_curve', struct(...
                    'type', 'PressureTransducer', ...
                    'sensor_range', 10, ...
                    'unit_str', 'psid') ...
                ) ...
            ), ...
            'fd_to_load', 'LN2 PT-3917 Press Sensor  Mon RAW', ...
            'fd_to_save', 'LN2 PT-3917 Press Sensor  Mon MCS', ...
            'output_units', 'psid' ...
            );
     struct( 'entry_str', 'MARS11ColHeight', ...
            'container', struct('MARS11ColHeight', ...
                struct('cal_curve', struct(...
                    'type', 'LiquidColumnHeight', ...
                    'commodity', 'LO2', ...
                    'pressure_units', 'psid', ...
                    'unit_str', 'in') ...
                ) ...
            ), ...
            'fd_to_load', 'LN2 PT-3917 Press Sensor  Mon MCS', ...
            'fd_to_save', 'MARS-11 Liquid Column Height', ...
            'output_units', 'psid' ...
            );
    struct( 'entry_str', 'MARS11VolGal', ...
            'container', struct('MARS11VolGal', ...
                struct('cal_curve', struct(...
                    'type', 'TorrosphericalTank', ...
                    'tank_radius', 112, ...
                    'cyl_length', 715, ...
                    'unit_str', 'psid') ...
                ) ...
            ), ...
            'fd_to_load', 'MARS-11 Liquid Column Height', ...
            'fd_to_save', 'MARS-11 Liquid Volume Gallons', ...
            'output_units', 'psid' ...
            );
    struct( 'entry_str', 'MARS11VolPercent', ...
            'container', struct('MARS11VolPercent', ...
                struct('cal_curve', struct(...
                    'type', 'TorrosphericalTank', ...
                    'tank_radius', 112, ...
                    'cyl_length', 715, ...
                    'return_mode', 'percent', ...
                    'unit_str', 'psid') ...
                ) ...
            ), ...
            'fd_to_load', 'MARS-11 Liquid Column Height', ...
            'fd_to_save', 'MARS-11 Liquid Volume Percent', ...
            'output_units', 'psid' ...
            );

    % MARS-12 Calculations
    struct( 'entry_str', 'PT3918', ...
            'container', struct('PT3918', ...
                struct('cal_curve', struct(...
                    'type', 'PressureTransducer', ...
                    'sensor_range', 10, ...
                    'unit_str', 'psid') ...
                ) ...
            ), ...
            'fd_to_load', 'LN2 PT-3918 Press Sensor  Mon RAW', ...
            'fd_to_save', 'LN2 PT-3918 Press Sensor  Mon MCS', ...
            'output_units', 'psid' ...
            );
     struct( 'entry_str', 'MARS12ColHeight', ...
            'container', struct('MARS12ColHeight', ...
                struct('cal_curve', struct(...
                    'type', 'LiquidColumnHeight', ...
                    'commodity', 'LO2', ...
                    'pressure_units', 'psid', ...
                    'unit_str', 'in') ...
                ) ...
            ), ...
            'fd_to_load', 'LN2 PT-3918 Press Sensor  Mon MCS', ...
            'fd_to_save', 'MARS-12 Liquid Column Height', ...
            'output_units', 'psid' ...
            );
    struct( 'entry_str', 'MARS12VolGal', ...
            'container', struct('MARS12VolGal', ...
                struct('cal_curve', struct(...
                    'type', 'TorrosphericalTank', ...
                    'tank_radius', 112, ...
                    'cyl_length', 715, ...
                    'unit_str', 'psid') ...
                ) ...
            ), ...
            'fd_to_load', 'MARS-12 Liquid Column Height', ...
            'fd_to_save', 'MARS-12 Liquid Volume Gallons', ...
            'output_units', 'psid' ...
            );
    struct( 'entry_str', 'MARS12VolPercent', ...
            'container', struct('MARS12VolPercent', ...
                struct('cal_curve', struct(...
                    'type', 'TorrosphericalTank', ...
                    'tank_radius', 112, ...
                    'cyl_length', 715, ...
                    'return_mode', 'percent', ...
                    'unit_str', 'psid') ...
                ) ...
            ), ...
            'fd_to_load', 'MARS-12 Liquid Column Height', ...
            'fd_to_save', 'MARS-12 Liquid Volume Percent', ...
            'output_units', 'psid' ...
            );
];


%%



for n = 1:numel(to_process)
    this_field_str = to_process(n).entry_str;
    this_continer = to_process(n).container.(this_field_str);
    this_fd_to_load = to_process(n).fd_to_load;
    this_fd_to_save = to_process(n).fd_to_save;
    this_output_units = to_process(n).output_units;

    this_cal_curve = this_continer.cal_curve;

    fd = load_fd_by_name(this_fd_to_load);

    % Use the FD struct that's loaded and build the correct metadata for
    % the output FD. The `proc_vals` will be added to the fd.ts at the end
    % of the switch statement.
    switch this_cal_curve.type
        case 'PressureTransducer'
            fprintf('Processing %s as a PressureSensor\n', this_fd_to_load)

            proc_vals = apply_calibraiton_curve( ...
                'PressureTransducer', ...
                this_cal_curve, ...
                fd.ts.Data);

            temp_fd = getDataParams(this_fd_to_save);
            
            fd.ID = temp_fd.ID;
            fd.Type = temp_fd.Type;
            fd.System = temp_fd.System;


        case 'LiquidColumnHeight'
            fprintf('Processing %s as a LiquidColumnHeight\n', this_fd_to_load)
            
            proc_vals = apply_calibraiton_curve(...
                'LiquidColumnHeight', ...
                this_cal_curve, ...
                fd.ts.Data);

            toks = split(this_fd_to_save);
            % Expect the form: 'MARS-144 Liquid Volume Gallons'
            fd.System = 'LO2'; % Hack for now
            fd.ID = toks{end}; % Gallons, Height, Percent
            fd.Type = toks{1}; % Tank name

        case {'HemisphericalTank', 'TorrosphericalTank'}
            fprintf('Processing %s as a %s\n', this_fd_to_load, this_cal_curve.type)

            proc_vals = apply_calibraiton_curve( ...
                this_cal_curve.type, ...
                this_cal_curve, ...
                fd.ts.Data);

            toks = split(this_fd_to_save);
            % Expect the form: 'MARS-144 Liquid Volume Gallons'
            fd.System = 'LO2'; % Hack for now
            fd.ID = toks{end}; % Gallons, Height, Percent
            fd.Type = toks{1}; % Tank name

        otherwise
            warning('No function defined for cal curve of type: %s', this_cal_curve.type);
            continue
    end

    fd.FullString = this_fd_to_save;
    fd.ts.Data = proc_vals;
    fd.ts.Name = fd.FullString;

    try
        fd.ts.DataInfo.Units = this_output_units;
    catch
        warning('Unable to apply unit string to FD: %s', this_fd_to_save)
    end

    save_fd_to_disk(fd);

end


